live_config_reload = true

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"
vblank_mode = "1"

[font]
size = 17

[font.bold]
family = "ComicShannsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ComicShannsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ComicShannsMono Nerd Font"
style = "Italic"

[font.normal]
family = "ComicShannsMono Nerd Font"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 10
y = 0
